stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t market-backend-image .

test-job:
  stage: test
  script:
    - docker run --rm market-backend-image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose down --remove-orphans
    - docker compose up -d
