apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sofa-server.fullname" . }}
  labels:
    {{- include "sofa-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sofa-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force pod restart when ConfigMap or Secret changes.
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sofa-server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "sofa-server.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "sofa-server.fullname" . }}
            - secretRef:
                name: {{ include "sofa-server.fullname" . }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - name: local-storage
              mountPath: {{ .Values.storage.mountPath }}
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: {{ include "sofa-server.fullname" . }}-storage
      {{- end }}
