apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sofa-server.fullname" . }}
  labels:
    {{- include "sofa-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
